// pawno/include/systems/colors.inc

#if defined _systems_colors_included
    #endinput
#endif
#define _systems_colors_included

// Definire Culori Hex
#define COLOR_LIGHTPURPLE   0xBF94E4FF  // Mov deschis
#define COLOR_RED           0xE84C3DFF  // Rosu (Erori)
#define COLOR_GREY          0xAFAFAFFF  // Gri (Sintaxa)
#define COLOR_WHITE         0xFFFFFFFF  // Alb (General)

// Definire Culori pentru String-uri (Embed)
#define C_LIGHTPURPLE       "{BF94E4}"
#define C_RED               "{E84C3D}"
#define C_GREY              "{AFAFAF}"
#define C_WHITE             "{FFFFFF}"